version: "3"
services:
  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - ./data/rethinkdb/rdb01:/data
    command: rethinkdb --bind all --initial-password rdb-init-pwd-zxcvZXCV
  api:
    build: ./api
    command: node index.js
    volumes:
      - ./api:/api
    ports:
      - 3030:3030
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - DB_DATABASE=leegdb
      - DB_USER=admin
      - DB_PASS=rdb-init-pwd-zxcvZXCV
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    depends_on:
      - rethinkdb
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    environment:
      - API='http://localhost:3030'
      - WEBSOCKET='http://localhost:3030'
    working_dir: /app
    command: npm run dev
    depends_on:
      - api
