version: "3"
services:
  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - ./data/rethinkdb/rdb01:/data
    command: rethinkdb --bind all --initial-password rdb-init-pwd-zxcvZXCV
    ports:
      - 8000:8080
  redis:
    image: redis:alpine
  api:
    build: ./api
    command: node app.js
    volumes:
      - ./api:/api
    ports:
      - 3030:3030
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - DB_DATABASE=leegdb
      - DB_USER=admin
      - DB_PASS=rdb-init-pwd-zxcvZXCV
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=redis-secret-foo-bar-baz-zzz
      - SESSION_RETRIES=5
      - APP_REDIRECT_URL=http://localhost:8080/
    depends_on:
      - rethinkdb
      - redis
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    environment:
      - API=http://localhost:3030
      - WEBSOCKET=http://localhost:3030
    working_dir: /app
    command: npm run dev
    depends_on:
      - api
